version: '3.5'

services:
  goerli-explorer:
    restart: on-failure
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: npm run dev
    depends_on:
      - parity-rpc
      - pantheon-rpc
    volumes:
      - .:/usr/app
      - explorer-node-modules:/usr/app/node_modules
    ports:
      - ${SERVER_HOST_PORT-3000}:3000
    environment:
      - CACHE_DRIVER=${CACHE_DRIVER:-redis}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}

  parity-rpc:
    image: nodefactory/parity-goerly:alpine-clique-v5
    command: --jsonrpc-cors=all --jsonrpc-port=8545 --jsonrpc-interface=0.0.0.0 --chain=goerli --tracing=on --fat-db=on --pruning=archive --base-path /home/parity/.local/share/io.parity.ethereum/
    volumes:
      - parity-chain-data:/home/parity/.local/share/io.parity.ethereum

  pantheon-rpc:
    image: pegasyseng/pantheon:latest
    command: --network=goerli  --rpc-http-enabled --host-whitelist=*
    volumes:
      - pantheon-chain-data:/var/lib/pantheon

  redis:
    image: redis:5-alpine
    command: --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  explorer-node-modules:
  parity-chain-data:
  pantheon-chain-data:
  redis-data:
